/** Authentication variables */
const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const SIGNUP = "SIGNUP";

export { LOGIN, LOGOUT, SIGNUP };

/** Notes functions variables */
const FETCH_NOTES = "FETCH_NOTES";
const ADD_NOTE = "ADD_NOTE";
const DELETE_NOTE = "DELETE_NOTE";
const EDIT_NOTE = "EDIT_NOTE";
const CLEAR_NOTES = "CLEAR_NOTES";

export { FETCH_NOTES, ADD_NOTE, DELETE_NOTE, EDIT_NOTE, CLEAR_NOTES };

/** Trash function variables */
const LOAD_NOTES_IN_TRASH = "LOAD_NOTES_IN_TRASH";
const MOVE_TO_TRASH = "MOVE_TO_TRASH";
const RESTORE_FROM_TRASH = "REMOVE_FROM_TRASH";
const CLEAR_TRASH = "CLEAR_TRASH";
const DELETE_FROM_TRASH = "DELETE_FROM_TRASH";

export {
  LOAD_NOTES_IN_TRASH,
  MOVE_TO_TRASH,
  RESTORE_FROM_TRASH,
  CLEAR_TRASH,
  DELETE_FROM_TRASH,
};

/** Archive function variables */
const ADD_TO_ARCHIVE = "ADD_TO_ARCHIVE";
const FETCH_NOTES_IN_ARCHIVE = "FETCH_NOTES_IN_ARCHIVE";
const REMOVE_FROM_ARCHIVE = "REMOVE_FROM_ARCHIVE";
const DELETE_FROM_ARCHIVE = "DELETE_FROM_ARCHIVE";
const CLEAR_ARCHIVES = "CLEAR_ARCHIVES";

export {
  ADD_TO_ARCHIVE,
  FETCH_NOTES_IN_ARCHIVE,
  REMOVE_FROM_ARCHIVE,
  DELETE_FROM_ARCHIVE,
  CLEAR_ARCHIVES,
};

/** Tags variables */
const ADD_TAG = "ADD_TAG";

export { ADD_TAG };

/** Note filter variables */
const SORT_BY_DATE = "SORT_BY_DATE";
const SORT_BY_PRIORITY = "SORT_BY_PRIORITY";
const CLEAR_FILTERS = "CLEAR_FILTERS";
const LOW_TO_HIGH_PRIORITY = "LOW_TO_HIGH_PRIORITY";
const HIGH_TO_LOW_PRIORITY = "HIGH_TO_LOW_PRIORITY";
const OLDEST_FIRST = "OLDEST_FIRST";
const NEWEST_FIRST = "NEWEST_FIRST";

export {
  SORT_BY_DATE,
  SORT_BY_PRIORITY,
  CLEAR_FILTERS,
  LOW_TO_HIGH_PRIORITY,
  HIGH_TO_LOW_PRIORITY,
  OLDEST_FIRST,
  NEWEST_FIRST,
};
