/** Authentication variables */
const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const SIGNUP = "SIGNUP";

export { LOGIN, LOGOUT, SIGNUP };

/** Notes functions variables */
const FETCH_NOTES = "FETCH_NOTES";
const ADD_NOTE = "ADD_NOTE";
const DELETE_NOTE = "DELETE_NOTE";
const EDIT_NOTE = "EDIT_NOTE";
const CLEAR_NOTES = "CLEAR_NOTES";

export { FETCH_NOTES, ADD_NOTE, DELETE_NOTE, EDIT_NOTE, CLEAR_NOTES };

/** Trash function variables */
const LOAD_NOTES_IN_TRASH = "LOAD_NOTES_IN_TRASH";
const MOVE_TO_TRASH = "MOVE_TO_TRASH";
const RESTORE_FROM_TRASH = "REMOVE_FROM_TRASH";
const CLEAR_TRASH = "CLEAR_TRASH";
const DELETE_FROM_TRASH = "DELETE_FROM_TRASH";

export {
  LOAD_NOTES_IN_TRASH,
  MOVE_TO_TRASH,
  RESTORE_FROM_TRASH,
  CLEAR_TRASH,
  DELETE_FROM_TRASH,
};
